"""
NEXUS Phase 15: Demo Mode API Router
Endpoints:
- POST /demo/load: Loads synthetic demo assets into NEXUS ingestion & vector databases.
- POST /demo/run: Executes full 10-stage multimodal competition workflow.
- GET /demo/status: Inspects demo mode status and air-gapped hardware telemetry.
- GET /demo/report: Fetches the latest generated competition action report.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from backend.database import get_db
from backend.demo.service import demo_orchestrator
from backend.logger import get_logger

logger = get_logger("nexus.routes_demo")

router = APIRouter(prefix="/demo", tags=["Competition Demo Mode"])


@router.post("/load", summary="Load Synthetic Demonstration Dataset")
def load_demo_dataset(db: Session = Depends(get_db)):
    """Loads and indexes the 5 synthetic assets from demo_data/."""
    try:
        res = demo_orchestrator.load_demo_dataset(db=db)
        return res
    except Exception as e:
        logger.error(f"Failed to load demo dataset: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to load synthetic demo dataset: {str(e)}",
        )


@router.post("/run", summary="Run Deterministic Competition Demo Workflow")
def run_competition_demo(db: Session = Depends(get_db)):
    """
    Executes the 10-stage multimodal competition workflow:
    Goal -> Plan -> Document Discovery -> OCR -> Retrieval -> Vision -> Local Reasoning -> Evidence -> Verification -> Report Generation.
    """
    try:
        res = demo_orchestrator.run_competition_demo(db=db)
        return res
    except Exception as e:
        logger.error(f"Failed to execute competition demo: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to execute competition demo: {str(e)}",
        )


@router.get("/status", summary="Get Demo Mode & Hardware Status")
def get_demo_status():
    """Returns DEMO_MODE activation, air-gap network status, and NPU silicon state."""
    hw = demo_orchestrator.get_hardware_status()
    return {
        "demo_mode": "ACTIVE" if demo_orchestrator.is_demo_mode else "READY",
        "hardware_status": hw,
        "has_last_run": demo_orchestrator._last_run_result is not None,
    }


@router.get("/report", summary="Fetch Generated Competition Action Report")
def get_demo_report():
    """Returns the markdown action report generated by the competition demo."""
    if not demo_orchestrator._last_run_result:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No demo action report generated yet. Run /demo/run first.",
        )
    return demo_orchestrator._last_run_result.get("report", {})
