"""
NEXUS Local Language Model API Routes
Provides grounded question-answering strictly utilizing provided local context.
No filesystem access, no tool execution, no cloud fallback.
"""

from typing import List, Optional
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from backend.interfaces.base import ModelStatus
from backend.interfaces import model_registry
from backend.models_local.llama_language import LocalLlamaModel
from backend.logger import get_logger

logger = get_logger("nexus.routes_llm")

llm_router = APIRouter(prefix="/llm", tags=["Language Model"])

# Singleton local model reference
local_llama_model = LocalLlamaModel(auto_load=False)
model_registry.register_model("language", local_llama_model)


class LLMQueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="The user's question")
    context: List[str] = Field(default_factory=list, description="Grounding context items/chunks")


class LLMQueryResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer generated by local model")
    sources: List[str] = Field(default_factory=list, description="Echoed context sources used")


@llm_router.post(
    "/query",
    response_model=LLMQueryResponse,
    summary="Local Grounded Question-Answering",
    description="Queries the offline local language model using provided context without external calls.",
)
def query_llm(request: LLMQueryRequest):
    question_clean = request.question.strip()
    if not question_clean:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Question cannot be empty or blank.",
        )

    # Check model health
    health = local_llama_model.health_check()
    if health != ModelStatus.READY:
        # Attempt loading
        if not local_llama_model.load():
            logger.error(f"Local LLM unavailable: {local_llama_model._load_error}")
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail=f"Local language model unavailable: {local_llama_model._load_error or 'Weights missing'}",
            )

    # Construct context-grounded prompt
    if request.context:
        context_blocks = "\n".join([f"- {c.strip()}" for c in request.context if c.strip()])
        user_prompt = (
            f"Context:\n{context_blocks}\n\n"
            f"Question: {question_clean}\n\n"
            f"Answer:"
        )
    else:
        user_prompt = (
            f"Question: {question_clean}\n\n"
            f"Answer:"
        )

    system_prompt = (
        "You are NEXUS, an offline AI assistant. "
        "Answer the question concisely and truthfully using the provided context directly."
    )

    try:
        answer = local_llama_model.generate(
            prompt=user_prompt,
            system_prompt=system_prompt,
            max_tokens=256,
            temperature=0.1,
            timeout_seconds=30.0,
        )
        return LLMQueryResponse(
            answer=answer,
            sources=request.context,
        )
    except TimeoutError as te:
        logger.error(f"LLM inference timed out: {te}")
        raise HTTPException(
            status_code=status.HTTP_408_REQUEST_TIMEOUT,
            detail="Inference timed out during local model execution.",
        )
    except RuntimeError as re:
        logger.error(f"LLM runtime error: {re}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(re),
        )
    except Exception as e:
        logger.error(f"Unexpected error in LLM query: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Internal model error: {str(e)}",
        )
